#!/usr/bin/env bash

JAVACMD=java
PROGRAM_ARGS=""
JAVA_ARGS=""

for opt in "$@"
do
  case $opt in
    *)
      PROGRAM_ARGS="$PROGRAM_ARGS $opt" ;;
  esac
done

set -x

$JAVACMD $JAVA_ARGS -jar build/libs/pyterpreter-all-1.0-SNAPSHOT.jar $PROGRAM_ARGS
